[package]
name = "nix-store"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.79"
nix-util = { path = "../nix-util" }
nix-c-raw = { path = "../nix-c-raw" }
lazy_static = "1.4.0"
