[workspace]
members = [
    "nix-bindings-bindgen-raw",
    "nix-bindings-expr",
    "nix-bindings-fetchers",
    "nix-bindings-flake",
    "nix-bindings-store",
    "nix-bindings-util",
]
resolver = "2"
